name: Github Actions Test

on:
  push:
    branches: [ develop ]

jobs:
  job1:
   # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Run node.js with env
        run: node client.js
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432

      - name: Run bash script
        run: ./bash_script.sh
        shell: bash
